import ROLES from "./role.js";

const PERMISSIONS = Object.freeze({
  ADMIN_ONLY: [ROLES.ADMIN],

  FORMATEUR_ONLY: [ROLES.FORMATEUR],

  ETUDIANT_ONLY: [ROLES.ETUDIANT],

  ADMIN_FORMATEUR: [ROLES.ADMIN, ROLES.FORMATEUR],

  ALL: [ROLES.ADMIN, ROLES.FORMATEUR, ROLES.ETUDIANT],
});

export default PERMISSIONS;
